### ISSUE TITLE
初始化本端高级UDP协议套接字失败。原因：应用程序的名称不正确

### ISSUE THREAD

**Issue by m733338844** [cyz7758520/Android_audio_talkback_demo_program#5]
MediaPocsThrd: 初始化本端高级UDP协议套接字[192.168.16.106:12345]失败。原因：应用程序的名称不正确。当前应用程序的名称：com.xxxx。

**Comment by cyz7758520** [comment]
抱歉，这个是收费功能，你可以用免费功能就没有这个报错了。
