### ISSUE TITLE
对比WebRTC有什么优势？

### ISSUE THREAD

**Issue by mallxiaodoudou** [cyz7758520/Android_audio_talkback_demo_program#6]
实时音视频通信已经有比较成熟与完善的解决方案WebRTC。并且支持跨端通信，我想问一下自己这么实现的话对比WebRTC有什么优缺点吗？

**Comment by cyz7758520** [comment]
资源占用比webrtc小，可以方便集成到自己的app，不用webrtc那么复杂的部署，装上app就能用，支持录音录像，回音消除应该比webrtc处理好一些，等等。

**Comment by cyz7758520** [comment]
WebRtc相对来说功能强大很多，但使用也很麻烦。

**Comment by mallxiaodoudou** [comment]
感谢回复，您这种方案好像只能用于本地局域网吧，如果是互联网对线的话能实现吗？能不能像WebRTC那样搭建虚拟局域网让两端实时音视频？

**Comment by cyz7758520** [comment]
互联网也可以使用，不过需要公网IP，如果两边都是局域网的话，需要做内网穿透就能实现互联网对讲了。
