### ISSUE TITLE
请问我该如何接入大神的代码实现一对多的视频会议？

### ISSUE THREAD

**Issue by flexolink-sdk** [cyz7758520/Android_audio_talkback_demo_program#7]
我有一台设备想要验证一下它的性能，看看它编码的同时，做5个解码显示，我该如何做？

**Comment by cyz7758520** [comment]
我猜你应该是想测试多人的对讲情况，目前demo还不支持多人的情况。
你如果不嫌麻烦的话，你可以手动写个测试程序，手动创建编码器和解码器，然后手动做编码和解码来测试。

**Comment by flexolink-sdk** [comment]
谢谢回复，对音视频这块懂得不多，我本来想在您的app demo基础下，删除一些功能，保留局域网通信，并在客户端那头多创建几个视频输出窗口（显示一样的内容也行，只要是多个解码就好），多搞几个MyMediaPocsThrd，一 一对应窗口显示，但好像只能创建一个Ntwk的连接，会报错。大神你说我该怎么最小的方式改动您的代码来实现这个功能

**Comment by cyz7758520** [comment]
要实现多人的对讲还挺麻烦的，要改协议，还要改代码流程，要改的地方蛮多，我后续会推出多人对讲的版本的，感谢关注！

**Comment by flexolink-sdk** [comment]
好的，持续关注！

**Comment by cyz7758520** [comment]
现在已经支持多人的音视频对讲了。
